<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE curso [
<!ELEMENT curso (titulo, unidad+)>

<!ELEMENT titulo (#PCDATA)>

<!ELEMENT unidad (lecciones)>
<!ATTLIST unidad titulo CDATA #REQUIRED>

<!ELEMENT lecciones (leccion+)>

<!ELEMENT leccion (#PCDATA)>
<!ATTLIST leccion titulo CDATA #REQUIRED>
]>

<curso>
<titulo> Introduccion a XML</titulo>

<unidad titulo="XML">
<lecciones>
<leccion titulo="Introduccion"> El contenido de la leccion...</leccion>
<leccion titulo="Documento bien formado"> El contenido de la leccion...</leccion>
<leccion titulo="Ejemplos de uso"> El contenido de la leccion...</leccion>
</lecciones>
</unidad>

</curso>