<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE NEWSPAPER [
<!ELEMENT NEWSPAPER (ARTICLE+, periodico, publisher, copyright)>
<!ELEMENT ARTICLE (HEADLINE,BYLINE,BODY,NOTES)>
<!ELEMENT HEADLINE (#PCDATA)>
<!ELEMENT BYLINE (#PCDATA)>
<!ELEMENT BODY (#PCDATA)>
<!ELEMENT NOTES (#PCDATA)>
<!ELEMENT periodico (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT copyright (#PCDATA)>


<!ATTLIST ARTICLE AUTHOR CDATA #REQUIRED>
<!ATTLIST ARTICLE DATE CDATA #IMPLIED>

<!ENTITY NEWSPAPER "Vervet Logic Times">
<!ENTITY PUBLISHER "Vervet Logic Press">
<!ENTITY COPYRIGHT "Copyright 1998 Vervet Logic Press">
]>

<NEWSPAPER>
  <ARTICLE AUTHOR="MDINFE" DATE="16-04-1968">
    <HEADLINE>REGERRGG</HEADLINE>
    <BYLINE>EFWAS</BYLINE>
    <BODY>EWFAAAAAAAAAAWERFWEAFDWE</BODY>
    <NOTES>FWAEFWEF</NOTES>
  </ARTICLE>
  <ARTICLE AUTHOR="MDINFE">
    <HEADLINE>REGERRGG</HEADLINE>
    <BYLINE>EFWAS</BYLINE>
    <BODY>EWFAAAAAAAAAAWERFWEAFDWE</BODY>
    <NOTES>FWAEFWEF</NOTES>
  </ARTICLE>
<periodico>&NEWSPAPER;</periodico>
 <publisher>&PUBLISHER;</publisher>
<copyright>&COPYRIGHT;</copyright>

</NEWSPAPER>
  